### ISSUE TITLE
feat: settings section

### ISSUE THREAD

**Issue by bryanlundberg** [ProyectLink/super-list-frontend#18]
![image](https://github.com/user-attachments/assets/0d3b78ca-68bf-4d15-bcdf-83b66e750b2a)

**Comment by bryanlundberg** [comment]
Hi, @namansharma3007 assigned 👌

Only need layout at the moment.

**Comment by namansharma3007** [comment]
Can you please add a label on both issues both issue #19 and #18 as hacktoberfest. So that it can be counted in my contributions.

**Comment by bryanlundberg** [comment]
> Can you please add a label on both issues both issue #19 and #18 as hacktoberfest. So that it can be counted in my contributions.

No need to label every issue as the repository has a hacktoberfest tag. It will count 🫰

**Comment by namansharma3007** [comment]
> > Can you please add a label on both issues both issue #19 and #18 as hacktoberfest. So that it can be counted in my contributions.
> 
> No need to label every issue as the repository has a hacktoberfest tag. It will count 🫰

Thanks for the input. I will develop it within 2 days.

**Comment by bryanlundberg** [comment]
> > > Can you please add a label on both issues both issue #19 and #18 as hacktoberfest. So that it can be counted in my contributions.
> > 
> > 
> > No need to label every issue as the repository has a hacktoberfest tag. It will count 🫰
> 
> Thanks for the input. I will develop it within 2 days. ✌️

Great
