### ISSUE TITLE
fix: homepage (icons section)

### ISSUE THREAD

**Issue by bryanlundberg** [ProyectLink/super-list-frontend#20]
Some browsers render as:
![image](https://github.com/user-attachments/assets/44544ffc-d09a-408b-b292-259ed8bea8f3)

desired:
![image](https://github.com/user-attachments/assets/a0b91207-2784-4159-ba5d-5da9429050c3)

**Comment by anshi05** [comment]
hey, I would like to contribute.

**Comment by bryanlundberg** [comment]
All yours @anshi05 probably the best solution would be got the SVG icons instead of Unicode characters

**Comment by anshi05** [comment]
Thanks! Sure I'll fix it.
