### ISSUE TITLE
feat: popup upgrade pro dialog

### ISSUE THREAD

**Issue by bryanlundberg** [ProyectLink/super-list-frontend#24]
Only layout the dialog component

![image](https://github.com/user-attachments/assets/3555732e-e74b-469e-a3bd-4f8d557975cf)

**Comment by adilkadivala** [comment]
let assign it me

**Comment by bryanlundberg** [comment]
There you go @adilkadivala !

**Comment by adilkadivala** [comment]
hey @bryanlundberg , I need some clearity in this issue,  can you please explain widely this issue, that what actually you want?

**Comment by bryanlundberg** [comment]
When you click the upgrade to pro button, it should open the dialog. 
Your task is implementing the dialog component and attach it to the onClick.

You will need to use the shadcn component to achieve it.

**Comment by adilkadivala** [comment]
okay got it,
