### ISSUE TITLE
Add Footer section

### ISSUE THREAD

**Issue by rahulpeacock** [ProyectLink/super-list-frontend#25]
I have seen the footer section for superlist and I would like to work on this issue

![image](https://github.com/user-attachments/assets/e81c9e4b-0557-4dd0-9f56-7e5e9a41f648)

Please assign this to me

**Comment by bryanlundberg** [comment]
Sure, why not 😅

**Comment by rahulpeacock** [comment]
@bryanlundberg I will start working on this issue

**Comment by rahulpeacock** [comment]
@bryanlundberg I have completed the footer section and made a PR at #31

**Comment by bryanlundberg** [comment]
#31
