### ISSUE TITLE
feat: logic for homepage buttons

### ISSUE THREAD

**Issue by bryanlundberg** [ProyectLink/super-list-frontend#26]
The navigation logic for the buttons on the homepage needs to be added:

The "Sign in" button should redirect to /login
The "Start today" button should redirect to /register

**Comment by raghuaanand** [comment]
@bryanlundberg can i start working on it under hacktoberfest?

**Comment by bryanlundberg** [comment]
> @bryanlundberg can i start working on it under hacktoberfest?
> 

Yes! Project is label with hacktoberfest tag.
