### ISSUE TITLE
Contribution.md

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [ProyectLink/super-list-frontend#27]
I think its a open source so it need and contribution file to do some clarification to the participant how to contribute in it.

assign me  this task with hactoberfest tag.

**Comment by Ananta2003** [comment]
I wanted to request your review of my PR (#34 ) that adds a CONTRIBUTING.md file. It provides guidelines for contributors and should help enhance collaboration.

**Comment by Mukesh-ghildiyal** [comment]
@Ananta2003 Trying to be oversmart brother 😂🤣

**Comment by bryanlundberg** [comment]
Yes you can @Mukesh-ghildiyal assigned

**Comment by bryanlundberg** [comment]
I was reviewing your @Ananta2003 PR. Something like that could work, btw sorry in this case Mukesh-ghildiyal request it first.

@Mukesh-ghildiyal  Just let's add more steps:

1. Fork
2. Create own Branch
3. Install dependencies…
4. How to turn on development server
5. Do the changes corresponding to the issue
6. Verify compile doing a build
7. Verify Project is updated with all last changes, resolve any conflict
8. Open PR.

**Comment by Ananta2003** [comment]
Ya Sure I closed my PR, he's right I should have asked earlier before raising PR it's all good
