### ISSUE TITLE
Add dark mode feature and footer section 

### ISSUE THREAD

**Issue by ankit071105** [ProyectLink/super-list-frontend#28]
Add dark mode feature and footer section with social media icons . Assigned me this issue i will make a complete responsive webpage

**Comment by Ananta2003** [comment]
Hey I would like to Contribute can you assign me ??

**Comment by spacedust26** [comment]
Hey @bryanlundberg ,
I'd like to work on adding the dark mode feature to the website by using a toggle button which swicthes between light and dark mode. Footer section seems to be assigned to someone else in another issue raised.
I'd be excited to start working on it under the hacktoberfest label.
Thankyou.

**Comment by bryanlundberg** [comment]
@ankit071105 

- Darkmode in progress #16 
- footer in progress #25

**Comment by bryanlundberg** [comment]
> Hey @bryanlundberg , I'd like to work on adding the dark mode feature to the website by using a toggle button which swicthes between light and dark mode. Footer section seems to be assigned to someone else in another issue raised. I'd be excited to start working on it under the hacktoberfest label. Thankyou.

You can check the original superlist.com page and open an issue with something different you would like to clone. 👌
