### ISSUE TITLE
[Feature Addition] Application "Today" tasks deadline under Inbox

### ISSUE THREAD

**Issue by HarzhMehta** [ProyectLink/super-list-frontend#39]
I would like to add the Application "Today" tasks deadline section for the website.

**Comment by bryanlundberg** [comment]
Hi, can you include me a image of the section you want 👋

**Comment by HarzhMehta** [comment]
![Screenshot 2024-10-04 075045](https://github.com/user-attachments/assets/9fc44963-4809-487d-870c-84705b3b7e6b)
An issue is raised on 'index' section so i'd like to work on 'Today' (as seen in ss) if possible. This pg is under 'Web' button of the homepage

**Comment by bryanlundberg** [comment]
that page already exist if you manyally enter the url /today
