### ISSUE TITLE
Update navbar (app)

### ISSUE THREAD

**Issue by bryanlundberg** [ProyectLink/super-list-frontend#41]
This task requires including the missing paths, and make them clickable.

You must be able to click and navigate correctly.

![image](https://github.com/user-attachments/assets/a5329efe-ad42-4819-9577-32197c9291de)

**Comment by SirxChinni** [comment]
I would like to work on it.

**Comment by bryanlundberg** [comment]
Hi, @SirxChinni asigned 👌
